# Purity Jekyll Theme
#=====================

## Plugin Configurations

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed


## Globals

url:     www.strangerjesus.com
baseurl: 
email: dan@strangerjesus.com

title:    STRANGER JESUS
name:  Stranger Jesus
tagline:  Christianity for weirdos, mostly                             #Optional
description: After years of being a square peg trying to fit in round holes it became obvious that the effort just wasn't worth it. God said "Stop doing that!" But here's the thing&#59; I know lots and lots of other people who've tried to fit in with the church without much success but to varying degrees pain, shame and apathy. This show is for them. It's an effort to let people who might not otherwise have the opportunity hear (or overhear) good news.
keywords: Christianity church weirdos
timezone: America/Chicago
lang: English

author:
  name:     Daniel Schultz
  link:     /pages/dan.md
  photo:
    alt:    Daniel Schultz
    remote: 
    local: assets/images/pastordan.png

## Theme and Layout

# Defaults:
# ---------
# theme:
#   tooltips:    enabled
#   hover_light: enabled
#
# fonts:
#   base: Noto Sans
#   head: Montserrat
#   mono: Ubuntu Mono
#
# layout:
#   header:
#     style: scroll # (can be: scroll | fixed | disabled)
#   footer:
#     style: scroll # (can be: scroll | fixed | disabled)
#   sidebar:
#     style: left   # (can be: left | right | disabled)

layout:
  header:
    style: fixed
  sidebar:
    style: right

topmenu:
  Itunes:
    iTunes:
      url: https://itunes.apple.com/us/podcast/stranger-jesus/id1385819114
      title: 'Stranger Jesus on iTunes'
      icon: music
      color: blue
#  Soundcloud:
#    soundcloud:
#      url:   https://example.com
#      title: 'Stranger Jesus on Soundcloud'
#      icon:  soundcloud
#      color: orange
  LibSyn:
    libsyn:
      url: http://strangerjesus.libsyn.com
      title: 'Stranger Jesus on LibSyn'
      alt-icon: libsyn.svg
  GooglePlay:
    googleplay:
      url: https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Ignkvycsguee33lf3fbtxlet2ym?t%3DStranger_Jesus%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16
      title: 'Stranger Jesus on Google Play'
      alt-icon: google.svg
#  Stitcher:
#    stitcher:
#      url: 
#      title: 'Stranger Jesus on Stitcher'
#      icon:
#     color:
#  TuneIn:
#    tunein:
#      url: 
#      title: 'Stranger Jesus on TuneIn'
#      icon:
#     color:
  Mailchimp:
    mailchimp:
      url:  https://mailchi.mp/8e18f656201a/stranger-jesus-e-newsletter
      title: 'Sign up for our newsletter'
      alt-icon: mailchimp.svg
  Phone:
    phone:
      local: pages/phone.md
      title: 'Call the show!'
      icon: phone
      color: black
  Support:
    support:
      local: pages/support.md
      title: 'Oh God this feels so crass'
      icon:  dollar-sign
      color: green
  Contact:
    email:
      url: mailto:dan@strangerjesus.com
      title: 'email'
      icon: keyboard
      color: darkgray


sidemenu:
  Links:
    personal:
      local: pages/dan.md
      title: About Dan
      icon:  user
    show:
      local: pages/abouttheshow.md
      title: About the Show
      icon:  microphone
    split_1:
      type:  separator
    twitter:
      url:   https://twitter.com/pastordan
      title: Twitter
      icon:  twitter
    instagram:
      url:   https://www.instagram.com/rev.daniel.schultz/
      title: Instagram
      icon:  instagram
    facebook:
      url:   https://www.facebook.com/DanielSchultzWriter/
      title: Facebook
      icon:  facebook
    reddit:
      url:   https://www.reddit.com/user/strangerjesus/posts/
      title: Reddit
      icon:  reddit
    split_2:
      type:  separator
    support:
      local: pages/support.md
      title: Support
      icon:  dollar
